1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [4]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a2 = a.reshape(6, 2)
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a3 = a.reshape(3, 4)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a4 = a.reshape(4, 3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [11]:
a6 = a.reshape(2, -1)
a6

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
a7 = a.reshape(3, -1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a8 = a.reshape(6, -1)
a8

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
a9 = a.reshape(-1, 4)
a9

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
a10 = a.reshape(-1, 6)
a10

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [20]:
a5.ndim == 1

False

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив

In [21]:
b = np.random.randn(3, 4)
b

array([[ 0.91971284, -0.04875999,  0.13009542, -0.0666466 ],
       [ 0.59075802, -1.37487212, -2.68467479,  1.14371676],
       [-0.40972291,  0.44892698, -0.26291215,  1.17344555]])

In [24]:
b2 = b.reshape(1, -1)
b2

array([[ 0.91971284, -0.04875999,  0.13009542, -0.0666466 ,  0.59075802,
        -1.37487212, -2.68467479,  1.14371676, -0.40972291,  0.44892698,
        -0.26291215,  1.17344555]])

In [25]:
b.size == b2.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [31]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [32]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [34]:
 np.array_equal(a, b)

True

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

In [44]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [38]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [55]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [59]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [61]:
B.shape

(4, 4)

In [62]:
np.linalg.det(B)
# определитель равен 0 следовательно обратную матрицу вычислить не получится

0.0

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [65]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно

In [67]:
c = np.random.randint(0, 16, 16)
c

array([ 3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D

In [69]:
C = c.reshape(4, -4)
C

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [70]:
D = 10 * C + B
D

array([[ 35, 134, 163, 132],
       [ 84, 170, 126, 182],
       [113, 106, 209, 312],
       [132, 192, 252, 332]])

In [71]:
np.linalg.det(D)

21320000.000000034

In [73]:
np.linalg.matrix_rank(D)

4

In [74]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.0421257 , -0.04781989, -0.07423077,  0.11272233],
       [ 0.00713133,  0.01837899,  0.00807692, -0.02050094],
       [-0.00235084, -0.03018386, -0.02807692,  0.04386679],
       [ 0.01440901,  0.03129456,  0.04615385, -0.06324578]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [75]:
D_inv[D_inv <= 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.]])

In [76]:
E = np.where(D_inv, B, C)
B, C, E

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[ 3, 12, 14, 10],
        [ 7, 12,  4,  6],
        [ 9,  2,  6, 10],
        [10,  7,  4,  3]]),
 array([[  3,  12,  14,  32],
        [ 14,  50,  86,   6],
        [  9,   2,   6, 212],
        [ 32, 122, 212,   3]]))